import { Montserrat, Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/organisms/navbar";
import { Menu } from "@/statics/menu";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight:["300", "400", "500", "700"],
  variable: "--font-montserrat",
});

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas",
});

export const metadata = {
  title: "BIM CONSTRUCTION",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar
          menu={Menu}
        />
        {children}
      </body>
    </html>
  );
}
